# Generated by Django 4.2.7 on 2023-12-03 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='imageUrl',
        ),
    ]
