# Generated by Django 4.2.7 on 2023-12-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='Tours', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='default', null=True, upload_to='profile_pictures'),
        ),
    ]
