# Generated by Django 4.2.7 on 2023-12-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0004_userprofile_location_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='Toulouse', max_length=200),
        ),
    ]
