# Generated by Django 4.2.7 on 2023-12-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0005_alter_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tickets',
            field=models.IntegerField(default=1),
        ),
    ]
